spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guerreiras?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql444
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

   